"""empty message

Revision ID: 19212573100a
Revises: ead6f609e8d9
Create Date: 2023-09-25 02:44:30.809347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19212573100a'
down_revision = 'ead6f609e8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('birth_year', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('climate', sa.String(length=255), nullable=True),
    sa.Column('terrain', sa.String(length=255), nullable=True),
    sa.Column('population', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    op.drop_table('people')
    # ### end Alembic commands ###
